### ISSUE TITLE
Suggestions, mostly typos and inconsistencies

### ISSUE THREAD

**Issue by Ximalas** [trustedsec/SysmonCommunityGuide#17]
I've attached an annotated PDF. Please incorporate my suggestions as you see fit.
[TS_Sysmon_Community_Guide-duplex-friendly-with-comments.pdf](https://github.com/trustedsec/SysmonCommunityGuide/files/4198635/TS_Sysmon_Community_Guide-duplex-friendly-with-comments.pdf)

**Comment by darkoperator** [comment]
Since the PDF is generated via pandoc from the Markdown files could you make the recomendations as pull request to the markdown files under the v1.1 branch?
