### ISSUE TITLE
Setoolkit not working site cloning 

### ISSUE THREAD

**Issue by rigmod31** [trustedsec/SysmonCommunityGuide#26]
I have installed SET and all other functions seem fine but when I try site cloning it gives me this error 
errno 2 no such file or directory src/webattack/tabnabbing/source.jsI  please help with how I can solve this

**Comment by darkoperator** [comment]
This repo is for the Sysmon Community Guide

**Comment by rigmod31** [comment]
> This repo is for the Sysmon Community Guide
> 

So where do I ask for assistance

**Comment by DrSKiZZ** [comment]
> > This repo is for the Sysmon Community Guide
> 
> So where do I ask for assistance

Read through previous issues and see if something similar has occured and fixed ytour problem before posting.

https://github.com/trustedsec/social-engineer-toolkit/issues

**Comment by dstaulcu** [comment]
Haven’t seen activity in this project for a while. Glad to see it!  :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkoperator** [comment]
Sysmon has not changed in a while, now working on outlining videos to support the guide

**Comment by dstaulcu** [comment]
Oh cool. Thanks for the content!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
