### ISSUE TITLE
Markdown code blocks truncated in PDF

### ISSUE THREAD

**Issue by 2XXE-SRA** [trustedsec/SysmonCommunityGuide#4]
It looks like instances of Markdown code blocks are being truncated in the PDF version of the document. Examples: https://github.com/trustedsec/SysmonCommunityGuide/blob/master/install-and-configuration.md#installation-best-practice and https://github.com/trustedsec/SysmonCommunityGuide/blob/master/install-and-configuration.md#deployment-script

**Comment by darkoperator** [comment]
thanks for letting us know, working on a fix

**Comment by darkoperator** [comment]
download the PDF version again from the releases. Turned it to LaTex and then to PDF and it seems to have worked.

**Comment by 2XXE-SRA** [comment]
That seems to have fixed it. Thanks!

**Comment by darkoperator** [comment]
Thank you for reporting it :) now need to script this conversion and insertion process
